### PR TITLE
Home page changes and website fixes

### PR DESCRIPTION
**Pull request by ryanholder**
Some tweaks to the home page and some minor tweaks.

http://logsearch-website-pr16.apps.cityindex.logsearch.io/

### CODE REVIEW

**Comment by ryanholder** [comment]
retest this please

**Comment by le-bott** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearch-website-PRs/25/

**Build Log**
*last 50 lines*

 ```
[...truncated 247 lines...]
+ PULL_REQUEST=pr16
+ docker run --rm -t -v /var/vcap/sys/tmp/jenkins_slave/workspace/shared.releases.logsearch-website-PRs:/workspace -e CF_API=https://api.apps.cityindex.logsearch.io -e CF_APPS_DOMAIN=apps.cityindex.logsearch.io -e CF_USER=sudobot@labs.cityindex.com -e CF_PASSWD=**** -e CF_ORG=cityindex-logsearch-io -e CF_SPACE=develop -e APP=logsearch-website-pr16 -e RUN_SMOKE_TESTS=/workspace/labs-operations/meta/logsearch-website/run_smoke_tests.sh -e DIST_FOLDER=_site/ deploy /workspace/labs-operations/shared/build-environments/deploy/cf_deploy.sh
=====> Checking dependancies
Mon Jan 26 16:32:46 UTC 2015
       cf version 6.8.0-b15c536-2014-12-10T19:26:38+00:00
=====> Connecting to CF at https://api.apps.cityindex.logsearch.io as sudobot@labs.cityindex.com
Mon Jan 26 16:32:46 UTC 2015
Connecting from IP 54.76.94.126
       API endpoint: https://api.apps.cityindex.logsearch.io
       Authenticating...
       OK
       
       Targeted org cityindex-logsearch-io
       
       Targeted space develop
       
       
                          
       API endpoint:   https://api.apps.cityindex.logsearch.io (API version: 2.14.0)   
       User:           sudobot@labs.cityindex.com   
       Org:            cityindex-logsearch-io   
       Space:          develop   
=====> Pushing new version...
Mon Jan 26 16:32:48 UTC 2015
       Using manifest file /workspace/manifest.yml
       
       Creating app logsearch-website-pr16 in org cityindex-logsearch-io / space develop as sudobot@labs.cityindex.com...
       OK
       
       Creating route logsearch-website-pr16.apps.cityindex.logsearch.io...
       OK
       
       Binding logsearch-website-pr16.apps.cityindex.logsearch.io to logsearch-website-pr16...
       OK
       
       Uploading logsearch-website-pr16...
       FAILED
       Error uploading application.
       Server error, status code: 500, error code: 10001, message: An unknown error occurred.
       logsearch-website-pr16   stopped           0/1         64M      1G     logsearch-website-pr16.apps.cityindex.logsearch.io   
=====> Running smoke tests against logsearch-website-pr16
Mon Jan 26 16:32:49 UTC 2015
====> Running smoke tests against http://logsearch-website-pr16.apps.cityindex.logsearch.io
Checking status from IP 54.76.94.126
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Smoke tests failed :-# 
curl -s http://logsearch-website-pr16.apps.cityindex.logsearch.io returned:
404 Not Found: Requested route ('logsearch-website-pr16.apps.cityindex.logsearch.io') does not exist.
Build step 'Execute shell' marked build as failure
```
Test FAILed.

**Comment by ryanholder** [comment]
retest this please

**Comment by le-bott** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearch-website-PRs/26/

**Build Log**
*last 50 lines*

 ```
[...truncated 224 lines...]
+ cp /var/vcap/sys/tmp/jenkins_slave/workspace/shared.releases.logsearch-website-PRs/labs-operations/meta/logsearch-website/manifest.yml .
+ cp /var/vcap/sys/tmp/jenkins_slave/workspace/shared.releases.logsearch-website-PRs/labs-operations/meta/logsearch-website/Staticfile _site
+ cp /var/vcap/sys/tmp/jenkins_slave/workspace/shared.releases.logsearch-website-PRs/labs-operations/meta/logsearch-website/nginx.conf _site
[shared.releases.logsearch-website-PRs] $ /bin/sh -xe /tmp/hudson2678592411381949409.sh
+ echo origin/pr/16/merge
+ sed -r s/(origin|merge|\/)//g
+ PULL_REQUEST=pr16
+ docker run --rm -t -v /var/vcap/sys/tmp/jenkins_slave/workspace/shared.releases.logsearch-website-PRs:/workspace -e CF_API=https://api.apps.cityindex.logsearch.io -e CF_APPS_DOMAIN=apps.cityindex.logsearch.io -e CF_USER=sudobot@labs.cityindex.com -e CF_PASSWD=**** -e CF_ORG=cityindex-logsearch-io -e CF_SPACE=develop -e APP=logsearch-website-pr16 -e RUN_SMOKE_TESTS=/workspace/labs-operations/meta/logsearch-website/run_smoke_tests.sh -e DIST_FOLDER=_site/ deploy /workspace/labs-operations/shared/build-environments/deploy/cf_deploy.sh
=====> Checking dependancies
Mon Jan 26 16:35:37 UTC 2015
       cf version 6.8.0-b15c536-2014-12-10T19:26:38+00:00
=====> Connecting to CF at https://api.apps.cityindex.logsearch.io as sudobot@labs.cityindex.com
Mon Jan 26 16:35:37 UTC 2015
Connecting from IP 54.76.94.126
       API endpoint: https://api.apps.cityindex.logsearch.io
       Authenticating...
       OK
       
       Targeted org cityindex-logsearch-io
       
       Targeted space develop
       
       
                          
       API endpoint:   https://api.apps.cityindex.logsearch.io (API version: 2.14.0)   
       User:           sudobot@labs.cityindex.com   
       Org:            cityindex-logsearch-io   
       Space:          develop   
=====> Pushing new version...
Mon Jan 26 16:35:38 UTC 2015
       Using manifest file /workspace/manifest.yml
       
       Updating app logsearch-website-pr16 in org cityindex-logsearch-io / space develop as sudobot@labs.cityindex.com...
       OK
       
       Uploading logsearch-website-pr16...
       FAILED
       Error uploading application.
       Server error, status code: 500, error code: 10001, message: An unknown error occurred.
       logsearch-website-pr16   stopped           0/1         64M      1G     logsearch-website-pr16.apps.cityindex.logsearch.io   
=====> Running smoke tests against logsearch-website-pr16
Mon Jan 26 16:35:40 UTC 2015
====> Running smoke tests against http://logsearch-website-pr16.apps.cityindex.logsearch.io
Checking status from IP 54.76.94.126
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Smoke tests failed :-# 
curl -s http://logsearch-website-pr16.apps.cityindex.logsearch.io returned:
404 Not Found: Requested route ('logsearch-website-pr16.apps.cityindex.logsearch.io') does not exist.
Build step 'Execute shell' marked build as failure
```
Test FAILed.

**Comment by ryanholder** [comment]
retest this please

**Comment by le-bott** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearch-website-PRs/27/

**Build Log**
*last 50 lines*

 ```
[...truncated 224 lines...]
+ cp /var/vcap/sys/tmp/jenkins_slave/workspace/shared.releases.logsearch-website-PRs/labs-operations/meta/logsearch-website/manifest.yml .
+ cp /var/vcap/sys/tmp/jenkins_slave/workspace/shared.releases.logsearch-website-PRs/labs-operations/meta/logsearch-website/Staticfile _site
+ cp /var/vcap/sys/tmp/jenkins_slave/workspace/shared.releases.logsearch-website-PRs/labs-operations/meta/logsearch-website/nginx.conf _site
[shared.releases.logsearch-website-PRs] $ /bin/sh -xe /tmp/hudson3133351268833361021.sh
+ echo origin/pr/16/merge
+ sed -r s/(origin|merge|\/)//g
+ PULL_REQUEST=pr16
+ docker run --rm -t -v /var/vcap/sys/tmp/jenkins_slave/workspace/shared.releases.logsearch-website-PRs:/workspace -e CF_API=https://api.apps.cityindex.logsearch.io -e CF_APPS_DOMAIN=apps.cityindex.logsearch.io -e CF_USER=sudobot@labs.cityindex.com -e CF_PASSWD=**** -e CF_ORG=cityindex-logsearch-io -e CF_SPACE=develop -e APP=logsearch-website-pr16 -e RUN_SMOKE_TESTS=/workspace/labs-operations/meta/logsearch-website/run_smoke_tests.sh -e DIST_FOLDER=_site/ deploy /workspace/labs-operations/shared/build-environments/deploy/cf_deploy.sh
=====> Checking dependancies
Mon Jan 26 16:42:02 UTC 2015
       cf version 6.8.0-b15c536-2014-12-10T19:26:38+00:00
=====> Connecting to CF at https://api.apps.cityindex.logsearch.io as sudobot@labs.cityindex.com
Mon Jan 26 16:42:02 UTC 2015
Connecting from IP 54.76.94.126
       API endpoint: https://api.apps.cityindex.logsearch.io
       Authenticating...
       OK
       
       Targeted org cityindex-logsearch-io
       
       Targeted space develop
       
       
                          
       API endpoint:   https://api.apps.cityindex.logsearch.io (API version: 2.14.0)   
       User:           sudobot@labs.cityindex.com   
       Org:            cityindex-logsearch-io   
       Space:          develop   
=====> Pushing new version...
Mon Jan 26 16:42:04 UTC 2015
       Using manifest file /workspace/manifest.yml
       
       Updating app logsearch-website-pr16 in org cityindex-logsearch-io / space develop as sudobot@labs.cityindex.com...
       OK
       
       Uploading logsearch-website-pr16...
       FAILED
       Error uploading application.
       Server error, status code: 500, error code: 10001, message: An unknown error occurred.
       logsearch-website-pr16   stopped           0/1         64M      1G     logsearch-website-pr16.apps.cityindex.logsearch.io   
=====> Running smoke tests against logsearch-website-pr16
Mon Jan 26 16:42:05 UTC 2015
====> Running smoke tests against http://logsearch-website-pr16.apps.cityindex.logsearch.io
Checking status from IP 54.76.94.126
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Smoke tests failed :-# 
curl -s http://logsearch-website-pr16.apps.cityindex.logsearch.io returned:
404 Not Found: Requested route ('logsearch-website-pr16.apps.cityindex.logsearch.io') does not exist.
Build step 'Execute shell' marked build as failure
```
Test FAILed.

**Comment by ryanholder** [comment]
retest me please

**Comment by ryanholder** [comment]
retest this please

**Comment by le-bott** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearch-website-PRs/28/

**Build Log**
*last 50 lines*

 ```
[...truncated 224 lines...]
+ cp /var/vcap/sys/tmp/jenkins_slave/workspace/shared.releases.logsearch-website-PRs/labs-operations/meta/logsearch-website/manifest.yml .
+ cp /var/vcap/sys/tmp/jenkins_slave/workspace/shared.releases.logsearch-website-PRs/labs-operations/meta/logsearch-website/Staticfile _site
+ cp /var/vcap/sys/tmp/jenkins_slave/workspace/shared.releases.logsearch-website-PRs/labs-operations/meta/logsearch-website/nginx.conf _site
[shared.releases.logsearch-website-PRs] $ /bin/sh -xe /tmp/hudson3283541810492237876.sh
+ echo origin/pr/16/merge
+ sed -r s/(origin|merge|\/)//g
+ PULL_REQUEST=pr16
+ docker run --rm -t -v /var/vcap/sys/tmp/jenkins_slave/workspace/shared.releases.logsearch-website-PRs:/workspace -e CF_API=https://api.apps.cityindex.logsearch.io -e CF_APPS_DOMAIN=apps.cityindex.logsearch.io -e CF_USER=sudobot@labs.cityindex.com -e CF_PASSWD=**** -e CF_ORG=cityindex-logsearch-io -e CF_SPACE=develop -e APP=logsearch-website-pr16 -e RUN_SMOKE_TESTS=/workspace/labs-operations/meta/logsearch-website/run_smoke_tests.sh -e DIST_FOLDER=_site/ deploy /workspace/labs-operations/shared/build-environments/deploy/cf_deploy.sh
=====> Checking dependancies
Mon Jan 26 16:51:12 UTC 2015
       cf version 6.8.0-b15c536-2014-12-10T19:26:38+00:00
=====> Connecting to CF at https://api.apps.cityindex.logsearch.io as sudobot@labs.cityindex.com
Mon Jan 26 16:51:12 UTC 2015
Connecting from IP 54.76.94.126
       API endpoint: https://api.apps.cityindex.logsearch.io
       Authenticating...
       OK
       
       Targeted org cityindex-logsearch-io
       
       Targeted space develop
       
       
                          
       API endpoint:   https://api.apps.cityindex.logsearch.io (API version: 2.14.0)   
       User:           sudobot@labs.cityindex.com   
       Org:            cityindex-logsearch-io   
       Space:          develop   
=====> Pushing new version...
Mon Jan 26 16:51:13 UTC 2015
       Using manifest file /workspace/manifest.yml
       
       Updating app logsearch-website-pr16 in org cityindex-logsearch-io / space develop as sudobot@labs.cityindex.com...
       OK
       
       Uploading logsearch-website-pr16...
       FAILED
       Error uploading application.
       Server error, status code: 500, error code: 10001, message: An unknown error occurred.
       logsearch-website-pr16   stopped           0/1         64M      1G     logsearch-website-pr16.apps.cityindex.logsearch.io   
=====> Running smoke tests against logsearch-website-pr16
Mon Jan 26 16:51:14 UTC 2015
====> Running smoke tests against http://logsearch-website-pr16.apps.cityindex.logsearch.io
Checking status from IP 54.76.94.126
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Smoke tests failed :-# 
curl -s http://logsearch-website-pr16.apps.cityindex.logsearch.io returned:
404 Not Found: Requested route ('logsearch-website-pr16.apps.cityindex.logsearch.io') does not exist.
Build step 'Execute shell' marked build as failure
```
Test FAILed.

**Comment by le-bott** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearch-website-PRs/29/

**Build Log**
*last 50 lines*

 ```
[...truncated 224 lines...]
+ cp /var/vcap/sys/tmp/jenkins_slave/workspace/shared.releases.logsearch-website-PRs/labs-operations/meta/logsearch-website/manifest.yml .
+ cp /var/vcap/sys/tmp/jenkins_slave/workspace/shared.releases.logsearch-website-PRs/labs-operations/meta/logsearch-website/Staticfile _site
+ cp /var/vcap/sys/tmp/jenkins_slave/workspace/shared.releases.logsearch-website-PRs/labs-operations/meta/logsearch-website/nginx.conf _site
[shared.releases.logsearch-website-PRs] $ /bin/sh -xe /tmp/hudson6505124032648233844.sh
+ echo origin/pr/16/merge
+ sed -r s/(origin|merge|\/)//g
+ PULL_REQUEST=pr16
+ docker run --rm -t -v /var/vcap/sys/tmp/jenkins_slave/workspace/shared.releases.logsearch-website-PRs:/workspace -e CF_API=https://api.apps.cityindex.logsearch.io -e CF_APPS_DOMAIN=apps.cityindex.logsearch.io -e CF_USER=sudobot@labs.cityindex.com -e CF_PASSWD=**** -e CF_ORG=cityindex-logsearch-io -e CF_SPACE=develop -e APP=logsearch-website-pr16 -e RUN_SMOKE_TESTS=/workspace/labs-operations/meta/logsearch-website/run_smoke_tests.sh -e DIST_FOLDER=_site/ deploy /workspace/labs-operations/shared/build-environments/deploy/cf_deploy.sh
=====> Checking dependancies
Mon Jan 26 17:08:17 UTC 2015
       cf version 6.8.0-b15c536-2014-12-10T19:26:38+00:00
=====> Connecting to CF at https://api.apps.cityindex.logsearch.io as sudobot@labs.cityindex.com
Mon Jan 26 17:08:17 UTC 2015
Connecting from IP 54.76.94.126
       API endpoint: https://api.apps.cityindex.logsearch.io
       Authenticating...
       OK
       
       Targeted org cityindex-logsearch-io
       
       Targeted space develop
       
       
                          
       API endpoint:   https://api.apps.cityindex.logsearch.io (API version: 2.14.0)   
       User:           sudobot@labs.cityindex.com   
       Org:            cityindex-logsearch-io   
       Space:          develop   
=====> Pushing new version...
Mon Jan 26 17:08:19 UTC 2015
       Using manifest file /workspace/manifest.yml
       
       Updating app logsearch-website-pr16 in org cityindex-logsearch-io / space develop as sudobot@labs.cityindex.com...
       OK
       
       Uploading logsearch-website-pr16...
       FAILED
       Error uploading application.
       Server error, status code: 500, error code: 10001, message: An unknown error occurred.
       logsearch-website-pr16   stopped           0/1         64M      1G     logsearch-website-pr16.apps.cityindex.logsearch.io   
=====> Running smoke tests against logsearch-website-pr16
Mon Jan 26 17:08:21 UTC 2015
====> Running smoke tests against http://logsearch-website-pr16.apps.cityindex.logsearch.io
Checking status from IP 54.76.94.126
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Smoke tests failed :-# 
curl -s http://logsearch-website-pr16.apps.cityindex.logsearch.io returned:
404 Not Found: Requested route ('logsearch-website-pr16.apps.cityindex.logsearch.io') does not exist.
Build step 'Execute shell' marked build as failure
```
Test FAILed.

**Comment by mrdavidlaing** [comment]
retest this please

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearch-website-PRs/30/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearch-website-PRs/32/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearch-website-PRs/33/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearch-website-PRs/34/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearch-website-PRs/35/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearch-website-PRs/36/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearch-website-PRs/37/Test PASSed.

**Comment by ryanholder** [comment]
@mrdavidlaing I changed favicon to new Kibana ELK and pushed here... Should we go ahead and merge just in case we run in to any issues on live ?

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearch-website-PRs/38/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearch-website-PRs/39/Test PASSed.

**Pull request merged**
