### PR TITLE
Snapshots with bosh and logsearch blog post

### PR DESCRIPTION
**Pull request by bonzofenix**
http://www.logsearch.io/blog/2015/08/snapshots-with-bosh-and-logsearch.html

### CODE REVIEW

**Comment by le-bott** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearch-website-PRs/50/

**Build Log**
*last 50 lines*

 ```
[EnvInject] - Inject global passwords.
GitHub pull request #22 of commit 59525363022380dd69590bacd8de2b80a9dbac07 automatically merged.
[EnvInject] - Loading node environment variables.
Building remotely on slave-z0.0 (docker ubuntu swarm) in workspace /var/vcap/sys/tmp/jenkins_slave/workspace/shared.releases.logsearch-website-PRs
Cloning the remote Git repository
Cloning repository https://github.com/logsearch/website.git
 > git init /var/vcap/sys/tmp/jenkins_slave/workspace/shared.releases.logsearch-website-PRs # timeout=10
ERROR: Error cloning remote repo 'origin'
ERROR: Error cloning remote repo 'origin'
```
Test FAILed.

**Comment by bonzofenix** [comment]
@mrdavidlaing can not see the build :(

**Comment by mrdavidlaing** [comment]
retest this please

**Comment by le-bott** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearch-website-PRs/51/

**Build Log**
*last 50 lines*

 ```
[EnvInject] - Inject global passwords.
GitHub pull request #22 of commit 59525363022380dd69590bacd8de2b80a9dbac07 automatically merged.
[EnvInject] - Loading node environment variables.
Building remotely on slave-z0.0 (docker ubuntu swarm) in workspace /var/vcap/sys/tmp/jenkins_slave/workspace/shared.releases.logsearch-website-PRs
Cloning the remote Git repository
Cloning repository https://github.com/logsearch/website.git
 > git init /var/vcap/sys/tmp/jenkins_slave/workspace/shared.releases.logsearch-website-PRs # timeout=10
ERROR: Error cloning remote repo 'origin'
ERROR: Error cloning remote repo 'origin'
```
Test FAILed.

**Comment by bonzofenix** [comment]
@mrdavidlaing I do not think there is something wrong with the blog post. From the output of le-bott I can not really tests whats wrong :/. Do you know what can this be related to ?

**Comment by mrdavidlaing** [comment]
retest this please

**Comment by bonzofenix** [comment]
@mrdavidlaing There is no doc on how to test this so I do not know what do to :/ Also the CI is not public so I do not know what it intends to do.

**Comment by mrdavidlaing** [comment]
@bonzofenix - sorry - that was a comment for the build server; which seems to be on its last legs.

There is nothing wrong with your PR; all the problems lie on the build server; which I am busy phasing out

**Comment by mrdavidlaing** [comment]
Since our automated PR -> website publish process seems to have died along with our old build server, I'm just going to merge this and publish it manually.

**Comment by mrdavidlaing** [comment]
@bonzofenix - Published at http://www.logsearch.io/blog/2015/08/snapshots-with-bosh-and-logsearch.html

Sorry for the delay!

**Pull request merged**
